Ast refactor
lambdaclass/concrete pull request #140
Opened 2024-05-31 20:39 UTC by kenarab

It has a dependency on PR #139.

It includes renaming structs for having a better convention for understanding code.

2024-06-03 16:46 UTC, juanbono commented on crates/concrete_ast/src/statements.rs
> -    pub target: LetStmtTarget,
here `target` and `value` sound more understandable.

2024-06-03 16:46 UTC, juanbono commented on crates/concrete_ast/src/expressions.rs
> +    pub match_expr: Box<Expression>,
why not just `expr`?

2024-06-03 16:46 UTC, juanbono commented on crates/concrete_ast/src/statements.rs
> -    pub condition: Option<Expression>,
I think `condition` is better than `cond`

2024-06-03 16:47 UTC, juanbono requested changes
See comments

2024-06-03 18:05 UTC, juanbono approved these changes

2024-06-03 18:43 UTC, kenarab commented
> > See comments
> 
> Applied all suggestions. There is still an open question to a comment

All reviewed changes closed

2024-06-05 13:59 UTC, igaray approved these changes

2024-06-07 19:32 UTC, merged