Add imports
lambdaclass/concrete pull request #79
Opened 2024-01-16 16:20 UTC by edg-l

Work in progress.

Current limitations (todo):
- No support for absolute paths when calling a function
- Import symbol renaming

The following compiles:
```
mod Simple {
    import Other.{hello1};
    import Other.Deep.{hello2};

    fn main() -> i64 {
        return hello1(2) + hello2(2);
    }
}

mod Other {
    pub fn hello1(x: i64) -> i64 {
        return x * 2;
    }

    mod Deep {
        pub fn hello2(x: i64) -> i64 {
            return x * 4;
        }
    }
}
```

2024-01-17 19:53 UTC, juanbono commented on crates/concrete_codegen_mlir/src/codegen.rs
> +            .expect("module not found");
This error is not very descriptive. We should improve the error message.

2024-01-17 19:53 UTC, juanbono commented on crates/concrete_codegen_mlir/src/codegen.rs
> +            .expect("failed to find import");
Same here

2024-01-17 19:53 UTC, juanbono commented on crates/concrete_codegen_mlir/src/codegen.rs
> +                    .expect("submodule not found");
same here.

2024-01-17 19:54 UTC, juanbono requested changes
Please improve error handling. We should specify the modules not found and things like that

2024-01-18 14:56 UTC, juanbono approved these changes

2024-01-22 19:13 UTC, igaray approved these changes

2024-01-22 19:13 UTC, merged